export class DefaultFilters {
    static effective = [
        '0 salarié',
        '1 ou 2 salariés',
        'Unités non employeuses',
        '3 a 5 salariés',
        '6 à 9 salariés',
        '10 à 19 salariés',
        '20 à 49 salariés',
        '50 à 99 salariés',
        '100 à 199 salariés',
        '200 à 249 salariés',
        '250 à 499 salariés',
        '500 à 999 salariés',
        '1000 à 1999 salariés',
        '2000 à 4999 salariés',
        '5000 à 9999 salariés',
        '10000 salariés et plus',
    ];

    static categories = [
        'PME',
        'ETI',
        'GE',
    ];

    static county = [
        {'name': 'Ain', 'value': '01'},
        {'name': 'Aisne', 'value': '02'},
        {'name': 'Allier', 'value': '03'},
        {'name': 'Alpes de Haute Provence', 'value': '04'},
        {'name': 'Hautes Alpes', 'value': '05'},
        {'name': 'Alpes Maritimes', 'value': '06'},
        {'name': 'Ardèche', 'value': '07'},
        {'name': 'Ardennes', 'value': '08'},
        {'name': 'Ariège', 'value': '09'},
        {'name': 'Aube', 'value': '10'},
        {'name': 'Aude', 'value': '11'},
        {'name': 'Aveyron', 'value': '12'},
        {'name': 'Bouches du Rhône', 'value': '13'},
        {'name': 'Calvados', 'value': '14'},
        {'name': 'Cantal', 'value': '15'},
        {'name': 'Charente', 'value': '16'},
        {'name': 'Charente Maritime', 'value': '17'},
        {'name': 'Cher', 'value': '18'},
        {'name': 'Corrèze', 'value': '19'},
        {'name': 'Corse du Sud', 'value': '2A'},
        {'name': 'Haute-Corse', 'value': '2B'},
        {'name': 'Côte d\'Or', 'value': '21'},
        {'name': 'Côtes d\'Armor', 'value': '22'},
        {'name': 'Creuse', 'value': '23'},
        {'name': 'Dordogne', 'value': '24'},
        {'name': 'Doubs', 'value': '25'},
        {'name': 'Drôme', 'value': '26'},
        {'name': 'Eure', 'value': '27'},
        {'name': 'Eure et Loir', 'value': '28'},
        {'name': 'Finistère', 'value': '29'},
        {'name': 'Gard', 'value': '30'},
        {'name': 'Haute Garonne', 'value': '31'},
        {'name': 'Gers', 'value': '32'},
        {'name': 'Gironde', 'value': '33'},
        {'name': 'Hérault', 'value': '34'},
        {'name': 'Ille et Vilaine', 'value': '35'},
        {'name': 'Indre', 'value': '36'},
        {'name': 'Indre et Loire', 'value': '37'},
        {'name': 'Isère', 'value': '38'},
        {'name': 'Jura', 'value': '39'},
        {'name': 'Landes', 'value': '40'},
        {'name': 'Loir et Cher', 'value': '41'},
        {'name': 'Loire', 'value': '42'},
        {'name': 'Haute Loire', 'value': '43'},
        {'name': 'Loire Atlantique', 'value': '44'},
        {'name': 'Loiret', 'value': '45'},
        {'name': 'Lot', 'value': '46'},
        {'name': 'Lot et Garonne', 'value': '47'},
        {'name': 'Lozère', 'value': '48'},
        {'name': 'Maine et Loire', 'value': '49'},
        {'name': 'Manche', 'value': '50'},
        {'name': 'Marne', 'value': '51'},
        {'name': 'Haute Marne', 'value': '52'},
        {'name': 'Mayenne', 'value': '53'},
        {'name': 'Meurthe et Moselle', 'value': '54'},
        {'name': 'Meuse', 'value': '55'},
        {'name': 'Morbihan', 'value': '56'},
        {'name': 'Moselle', 'value': '57'},
        {'name': 'Nièvre', 'value': '58'},
        {'name': 'Nord', 'value': '59'},
        {'name': 'Oise', 'value': '60'},
        {'name': 'Orne', 'value': '61'},
        {'name': 'Pas de Calais', 'value': '62'},
        {'name': 'Puy de Dôme', 'value': '63'},
        {'name': 'Pyrénées Atlantiques', 'value': '64'},
        {'name': 'Hautes Pyrénées', 'value': '65'},
        {'name': 'Pyrénées Orientales', 'value': '66'},
        {'name': 'Bas Rhin', 'value': '67'},
        {'name': 'Haut Rhin', 'value': '68'},
        {'name': 'Rhône', 'value': '69'},
        {'name': 'Haute Saône', 'value': '70'},
        {'name': 'Saône et Loire', 'value': '71'},
        {'name': 'Sarthe', 'value': '72'},
        {'name': 'Savoie', 'value': '73'},
        {'name': 'Haute Savoie', 'value': '74'},
        {'name': 'Paris', 'value': '75'},
        {'name': 'Seine Maritime', 'value': '76'},
        {'name': 'Seine et Marne', 'value': '77'},
        {'name': 'Yvelines', 'value': '78'},
        {'name': 'Deux Sèvres', 'value': '79'},
        {'name': 'Somme', 'value': '80'},
        {'name': 'Tarn', 'value': '81'},
        {'name': 'Tarn et Garonne', 'value': '82'},
        {'name': 'Var', 'value': '83'},
        {'name': 'Vaucluse', 'value': '84'},
        {'name': 'Vendée', 'value': '85'},
        {'name': 'Vienne', 'value': '86'},
        {'name': 'Haute Vienne', 'value': '87'},
        {'name': 'Vosges', 'value': '88'},
        {'name': 'Yonne', 'value': '89'},
        {'name': 'Territoire de Belfort', 'value': '90'},
        {'name': 'Essonne', 'value': '91'},
        {'name': 'Hauts de Seine', 'value': '92'},
        {'name': 'Seine Saint Denis', 'value': '93'},
        {'name': 'Val de Marne', 'value': '94'},
        {'name': 'Val d\'Oise', 'value': '95'},
        {'name': 'Guadeloupe', 'value': '9A'},
        {'name': 'Martinique', 'value': '9B'},
        {'name': 'Guyane', 'value': '9C'},
        {'name': 'Réunion', 'value': '9D'},
        {'name': 'Saint Pierre et Miquelon', 'value': ''},
        {'name': 'Mayotte', 'value': '9F'},
    ];

    static turnover = [
        'Moins de 0,5 millions d\'euros',
        'De 0,5 à moins de 1 millions d\'euros',
        'De 1 millions à moins de 2 millions d\'euros',
        'De 2 millions à moins de 5 millions d\'euros',
        'De 5 millions à moins de 10 millions d\'euros',
        'De 10 millions à moins de 20 millions d\'euros',
        'De 20 millions à moins de 50 millions d\'euros',
        'De 50 millions à moins de 100 millions d\'euros',
        'De 100 millions à moins de 200 millions d\'euros',
        '200 millions d\'euros ou plus',
    ];
}
