export class DefaultFilters {
    static effective = [
        {'name': 'Unités non employeuses', 'value': 'NN'},
        {'name': '0 salarié', 'value': '00'},
        {'name': '1 ou 2 salariés', 'value': '01'},
        {'name': '3 a 5 salariés', 'value': '02'},
        {'name': '6 à 9 salariés', 'value': '03'},
        {'name': '10 à 19 salariés', 'value': '11'},
        {'name': '20 à 49 salariés', 'value': '12'},
        {'name': '50 à 99 salariés', 'value': '21'},
        {'name': '100 à 199 salariés', 'value': '22'},
        {'name': '200 à 249 salariés', 'value': '31'},
        {'name': '250 à 499 salariés', 'value': '32'},
        {'name': '500 à 999 salariés', 'value': '41'},
        {'name': '1 000 à 1 999 salariés', 'value': '42'},
        {'name': '2 000 à 4 999 salariés', 'value': '51'},
        {'name': '5 000 à 9 999 salariés', 'value': '52'},
        {'name': '10 000 salariés et plus', 'value': '53'},
    ];

    static categories = [
        {'name': 'Petite ou moyenne entreprise', 'value': 'PME'},
        {'name': 'Entreprise de taille intermédiaire', 'value': 'ETI'},
        {'name': 'Grande entreprise', 'value': 'GE'},
    ];

    static county = [
        {'name': 'Ain', 'value': '01'},
        {'name': 'Aisne', 'value': '02'},
        {'name': 'Allier', 'value': '03'},
        {'name': 'Alpes de Haute Provence', 'value': '04'},
        {'name': 'Hautes Alpes', 'value': '05'},
        {'name': 'Alpes Maritimes', 'value': '06'},
        {'name': 'Ardèche', 'value': '07'},
        {'name': 'Ardennes', 'value': '08'},
        {'name': 'Ariège', 'value': '09'},
        {'name': 'Aube', 'value': '10'},
        {'name': 'Aude', 'value': '11'},
        {'name': 'Aveyron', 'value': '12'},
        {'name': 'Bouches du Rhône', 'value': '13'},
        {'name': 'Calvados', 'value': '14'},
        {'name': 'Cantal', 'value': '15'},
        {'name': 'Charente', 'value': '16'},
        {'name': 'Charente Maritime', 'value': '17'},
        {'name': 'Cher', 'value': '18'},
        {'name': 'Corrèze', 'value': '19'},
        {'name': 'Corse du Sud', 'value': '2A'},
        {'name': 'Haute-Corse', 'value': '2B'},
        {'name': 'Côte d\'Or', 'value': '21'},
        {'name': 'Côtes d\'Armor', 'value': '22'},
        {'name': 'Creuse', 'value': '23'},
        {'name': 'Dordogne', 'value': '24'},
        {'name': 'Doubs', 'value': '25'},
        {'name': 'Drôme', 'value': '26'},
        {'name': 'Eure', 'value': '27'},
        {'name': 'Eure et Loir', 'value': '28'},
        {'name': 'Finistère', 'value': '29'},
        {'name': 'Gard', 'value': '30'},
        {'name': 'Haute Garonne', 'value': '31'},
        {'name': 'Gers', 'value': '32'},
        {'name': 'Gironde', 'value': '33'},
        {'name': 'Hérault', 'value': '34'},
        {'name': 'Ille et Vilaine', 'value': '35'},
        {'name': 'Indre', 'value': '36'},
        {'name': 'Indre et Loire', 'value': '37'},
        {'name': 'Isère', 'value': '38'},
        {'name': 'Jura', 'value': '39'},
        {'name': 'Landes', 'value': '40'},
        {'name': 'Loir et Cher', 'value': '41'},
        {'name': 'Loire', 'value': '42'},
        {'name': 'Haute Loire', 'value': '43'},
        {'name': 'Loire Atlantique', 'value': '44'},
        {'name': 'Loiret', 'value': '45'},
        {'name': 'Lot', 'value': '46'},
        {'name': 'Lot et Garonne', 'value': '47'},
        {'name': 'Lozère', 'value': '48'},
        {'name': 'Maine et Loire', 'value': '49'},
        {'name': 'Manche', 'value': '50'},
        {'name': 'Marne', 'value': '51'},
        {'name': 'Haute Marne', 'value': '52'},
        {'name': 'Mayenne', 'value': '53'},
        {'name': 'Meurthe et Moselle', 'value': '54'},
        {'name': 'Meuse', 'value': '55'},
        {'name': 'Morbihan', 'value': '56'},
        {'name': 'Moselle', 'value': '57'},
        {'name': 'Nièvre', 'value': '58'},
        {'name': 'Nord', 'value': '59'},
        {'name': 'Oise', 'value': '60'},
        {'name': 'Orne', 'value': '61'},
        {'name': 'Pas de Calais', 'value': '62'},
        {'name': 'Puy de Dôme', 'value': '63'},
        {'name': 'Pyrénées Atlantiques', 'value': '64'},
        {'name': 'Hautes Pyrénées', 'value': '65'},
        {'name': 'Pyrénées Orientales', 'value': '66'},
        {'name': 'Bas Rhin', 'value': '67'},
        {'name': 'Haut Rhin', 'value': '68'},
        {'name': 'Rhône', 'value': '69'},
        {'name': 'Haute Saône', 'value': '70'},
        {'name': 'Saône et Loire', 'value': '71'},
        {'name': 'Sarthe', 'value': '72'},
        {'name': 'Savoie', 'value': '73'},
        {'name': 'Haute Savoie', 'value': '74'},
        {'name': 'Paris', 'value': '75'},
        {'name': 'Seine Maritime', 'value': '76'},
        {'name': 'Seine et Marne', 'value': '77'},
        {'name': 'Yvelines', 'value': '78'},
        {'name': 'Deux Sèvres', 'value': '79'},
        {'name': 'Somme', 'value': '80'},
        {'name': 'Tarn', 'value': '81'},
        {'name': 'Tarn et Garonne', 'value': '82'},
        {'name': 'Var', 'value': '83'},
        {'name': 'Vaucluse', 'value': '84'},
        {'name': 'Vendée', 'value': '85'},
        {'name': 'Vienne', 'value': '86'},
        {'name': 'Haute Vienne', 'value': '87'},
        {'name': 'Vosges', 'value': '88'},
        {'name': 'Yonne', 'value': '89'},
        {'name': 'Territoire de Belfort', 'value': '90'},
        {'name': 'Essonne', 'value': '91'},
        {'name': 'Hauts de Seine', 'value': '92'},
        {'name': 'Seine Saint Denis', 'value': '93'},
        {'name': 'Val de Marne', 'value': '94'},
        {'name': 'Val d\'Oise', 'value': '95'},
        {'name': 'Guadeloupe', 'value': '9A'},
        {'name': 'Martinique', 'value': '9B'},
        {'name': 'Guyane', 'value': '9C'},
        {'name': 'Réunion', 'value': '9D'},
        {'name': 'Saint Pierre et Miquelon', 'value': ''},
        {'name': 'Mayotte', 'value': '9F'},
    ];

    static turnover = [
        {'name': 'Moins de 0,5 millions d\'euros', 'value': '0'},
        {'name': 'De 0,5 millions d\'euros à 1 million d\'euros', 'value': '1'},
        {'name': 'De 1 millions à moins de 2 millions d\'euros', 'value': '2'},
        {'name': 'De 2 millions à moins de 5 millions d\'euros', 'value': '3'},
        {'name': 'De 5 millions à moins de 10 millions d\'euros', 'value': '4'},
        {'name': 'De 10 millions à moins de 20 millions d\'euros', 'value': '5'},
        {'name': 'De 20 millions à moins de 50 millions d\'euros', 'value': '6'},
        {'name': 'De 50 millions à moins de 100 millions d\'euros', 'value': '7'},
        {'name': 'De 100 millions à moins de 200 millions d\'euros', 'value': '8'},
        {'name': '200 millions d\'euros ou plus', 'value': '9'},
    ];

    static legalStatus = [
        {'name': 'Société civile immobilière', 'value': '6540'},
        {'name': 'Société à responsabilité limitée (sans autre indication)', 'value': '5499'},
        {'name': 'Association déclarée', 'value': '9220'},
        {'name': 'SAS, société par actions simplifiée', 'value': '5710'},
        {'name': 'SARL unipersonnelle', 'value': '5498'},
        {'name': 'Société par actions simplifiée à associé unique ou société par actions simplifiée unipersonnelle', 'value': '5720'},
        {'name': 'Autre société civile', 'value': '6599'},
        {'name': 'Syndicat de copropriété', 'value': '9110'},
        {'name': 'Commune et commune nouvelle', 'value': '7210'},
        {'name': 'Exploitation agricole à responsabilité limitée', 'value': '6598'},
        {'name': 'SA à conseil d\'administration (s.a.i.)', 'value': '5599'},
        {'name': 'Société étrangère non immatriculée au RCS', 'value': '3220'},
        {'name': 'Société en nom collectif', 'value': '5202'},
        {'name': 'Indivision entre personnes physiques', 'value': '2110'},
        {'name': 'Société civile immobilière de construction-vente', 'value': '6541'},
        {'name': 'Groupement agricole d\'exploitation en commun (GAEC)', 'value': '6533'},
        {'name': 'Société civile de moyens', 'value': '6589'},
        {'name': 'Société d\'exercice libéral à responsabilité limitée', 'value': '5485'},
        {'name': 'Société civile d\'exploitation agricole', 'value': '6597'},
        {'name': 'Groupement foncier agricole', 'value': '6534'},
        {'name': 'Société d\'exercice libéral à responsabilité limitée', 'value': '5485'},
        {'name': 'Société civile d\'exploitation agricole', 'value': '6597'},
        {'name': 'Groupement foncier agricole', 'value': '6534'},
        {'name': 'Centre communal d\'action sociale', 'value': '7361'},
        {'name': 'Société commerciale étrangère immatriculée au RCS', 'value': '3120'},
        {'name': 'Association de droit local (Bas-Rhin, Haut-Rhin et Moselle)', 'value': '9260'},
        {'name': 'Société créée de fait entre personnes physiques', 'value': '2210'},
        {'name': 'Autre groupement de droit privé non doté de la personnalité morale', 'value': '2900'},
        {'name': 'Coopérative d\'utilisation de matériel agricole en commun (CUMA)', 'value': '6316'},
        {'name': 'Commune', 'value': '7210'},
        {'name': 'SA à directoire (s.a.i.)', 'value': '5699'},
        {'name': 'Groupement d\'intérêt économique (GIE)', 'value': '6220'},
        {'name': 'SA nationale à conseil d\'administration', 'value': '5510'},
        {'name': 'Service déconcentré de l\'État à compétence (inter) départementale', 'value': '7172'},
        {'name': 'Établissement public local d\'enseignement', 'value': '7331'},
        {'name': 'Établissement d\'hospitalisation', 'value': '7364'},
        {'name': 'Caisse de crédit agricole mutuel', 'value': '6596'},
        {'name': 'Groupement forestier', 'value': '6536'},
        {'name': 'Association déclarée, reconnue d\'utilité publique', 'value': '5485'},
        {'name': 'Société coopérative agricole', 'value': '6317'},
        {'name': 'Mutuelle', 'value': '8210'},
        {'name': 'Syndicat intercommunal à vocation unique (SIVU)', 'value': '7353'},
        {'name': 'Groupement d\'employeurs', 'value': '9223'},
        {'name': 'Association foncière de remembrement', 'value': '7323'},
        {'name': 'Caisse des écoles', 'value': '7362'},
        {'name': 'Établissement public national à caractère industriel ou commercial non doté d\'un comptable public', 'value': '4120'},
        {'name': 'Association syndicale autorisée', 'value': '7321'},
        {'name': 'Département', 'value': '7220'},
        {'name': 'Comité central d\'entreprise', 'value': '8310'},
        {'name': 'Service déconcentré de l\'État à compétence (inter) régionale', 'value': '7171'},
        {'name': 'Établissement public national à caractère administratif', 'value': '7389'},
        {'name': 'Syndicat de salariés', 'value': '8410'},
        {'name': 'Société d\'exercice libéral par action simplifiée', 'value': '5785'},
        {'name': 'Syndicat patronal', 'value': '8420'},
        {'name': 'Communauté de communes', 'value': '7346'},
        {'name': 'Établissement public local social et médico-social', 'value': '7366'},
        {'name': 'Association syndicale libre', 'value': '9150'},
        {'name': 'SCP de notaires', 'value': '6565'},
        {'name': 'Autre personne morale de droit privé', 'value': '9900'},
        {'name': 'Autre SA coopérative à conseil d\'administration', 'value': '5560'},
        {'name': 'Établissement public national à caractère scientifique culturel et professionnel', 'value': '7383'},
        {'name': 'Fondation', 'value': '9300'},
        {'name': 'SCP d\'avocats', 'value': '6561'},
        {'name': 'SA d\'économie mixte à conseil d\'administration', 'value': '5515'},
        {'name': 'Caisse locale de crédit mutuel', 'value': '6595'},
        {'name': 'Comité d\'établissement', 'value': '8311'},
        {'name': 'Autre personne morale de droit étranger', 'value': '3290'},
        {'name': 'Société d\'assurance à forme mutuelle', 'value': '6411'},
        {'name': 'Syndicat mixte fermé', 'value': '7354'},
        {'name': 'Société coopérative de banque populaire', 'value': '5192'},
        {'name': 'Société en commandite par actions', 'value': '5308'},
        {'name': 'Autre SA coopérative à directoire', 'value': '5660'},
        {'name': 'Paroisse hors zone concordataire', 'value': '2700'},
        {'name': 'Assurance mutuelle agricole', 'value': '8250'},
        {'name': 'Régime général de la Sécurité Sociale', 'value': '8110'},
        {'name': 'Autre société civile professionnelle', 'value': '6585'},
        {'name': 'Société de Participations Financiere de Prof Libérale Société à responsabilité limitée (SPFPL SARL)', 'value': '5470'},
        {'name': 'Établissement public local à caractère industriel ou commercial', 'value': '4140'},
        {'name': 'Autre SARL coopérative', 'value': '5460'},
        {'name': 'Ordre professionnel ou assimilé', 'value': '8450'},
        {'name': 'Caisse (fédérale) de crédit mutuel', 'value': '5194'},
        {'name': 'Établissement public des cultes d\'Alsace-Lorraine', 'value': '7430'},
        {'name': 'Association non déclarée', 'value': '9210'},
        {'name': 'Organisme consulaire', 'value': '7381'},
        {'name': 'Syndicat intercommunal à vocation multiple (SIVOM)', 'value': '7345'},
        {'name': 'SARL coopérative ouvrière de production (SCOP)', 'value': '5458'},
        {'name': 'SCP d\'infirmiers', 'value': '6573'},
        {'name': 'Société en commandite simple', 'value': '5306'},
        {'name': 'Autre établissement public national administratif à compétence territoriale limitée', 'value': '7385'},
        {'name': 'Congrégation', 'value': '9240'},
        {'name': 'SCP de médecins', 'value': '6571'},
        {'name': 'SARL nationale', 'value': '5410'},
        {'name': 'SCP de vétérinaires', 'value': '6576'},
        {'name': 'Société civile d\'attribution', 'value': '6542'},
        {'name': 'Autre organisme professionnel', 'value': '8490'},
        {'name': '(Autre) Service déconcentré de l\'État à compétence territoriale', 'value': '7179'},
        {'name': 'Syndicat mixte ouvert', 'value': '7355'},
        {'name': 'Société en participation entre personnes physiques', 'value': '2310'},
        {'name': 'Groupement foncier et rural', 'value': '6538'},
        {'name': 'Communauté d\'agglomération', 'value': '7348'},
        {'name': 'SCP d\'huissiers', 'value': '6564'},
        {'name': 'Indivision avec personne morale', 'value': '2120'},
        {'name': 'Section de commune', 'value': '7313'},
    ];

    static cities = [
        {'name': 'PARIS 1', 'value': 'PARIS 1'},
        {'name': 'PARIS 2', 'value': 'PARIS 2'},
        {'name': 'PARIS 3', 'value': 'PARIS 3'},
        {'name': 'PARIS 4', 'value': 'PARIS 4'},
        {'name': 'PARIS 5', 'value': 'PARIS 5'},
        {'name': 'PARIS 6', 'value': 'PARIS 6'},
        {'name': 'PARIS 7', 'value': 'PARIS 7'},
        {'name': 'PARIS 8', 'value': 'PARIS 8'},
        {'name': 'PARIS 9', 'value': 'PARIS 9'},
        {'name': 'PARIS 10', 'value': 'PARIS 10'},
        {'name': 'PARIS 11', 'value': 'PARIS 11'},
        {'name': 'PARIS 12', 'value': 'PARIS 12'},
        {'name': 'PARIS 13', 'value': 'PARIS 13'},
        {'name': 'PARIS 14', 'value': 'PARIS 14'},
        {'name': 'PARIS 15', 'value': 'PARIS 15'},
        {'name': 'PARIS 16', 'value': 'PARIS 16'},
        {'name': 'PARIS 17', 'value': 'PARIS 17'},
        {'name': 'PARIS 19', 'value': 'PARIS 19'},
        {'name': 'PARIS 20', 'value': 'PARIS 20'},
        {'name': 'SAINT DENIS', 'value': 'SAINT DENIS'},
        {'name': 'TOULOUSE', 'value': 'TOULOUSE'},
        {'name': 'NICE', 'value': 'NICE'},
        {'name': 'BORDEAUX', 'value': 'BORDEAUX'},
        {'name': 'MONTPELLIER', 'value': 'MONTPELLIER'},
        {'name': 'NANTES', 'value': 'NANTES'},
        {'name': 'STRASBOURG', 'value': 'STRASBOURG'},
        {'name': 'LILLE', 'value': 'LILLE'},
        {'name': 'AIX EN PROVENCE', 'value': 'AIX EN PROVENCE'},
        {'name': 'RENNES', 'value': 'RENNES'},
        {'name': 'GRENOBLE', 'value': 'GRENOBLE'},
        {'name': 'FORT DE FRANCE', 'value': 'FORT DE FRANCE'},
        {'name': 'BOULOGNE BILLANCOURT', 'value': 'BOULOGNE BILLANCOURT'},
        {'name': 'NIMES', 'value': 'NIMES'},
        {'name': 'CANNES', 'value': 'CANNES'},
        {'name': 'SAINT ETIENNE', 'value': 'SAINT ETIENNE'},
        {'name': 'TOULON', 'value': 'TOULON'},
        {'name': 'ANNECY', 'value': 'ANNECY'},
        {'name': 'DIJON', 'value': 'DIJON'},
        {'name': 'PERPIGNAN', 'value': 'PERPIGNAN'},
        {'name': 'REIMS', 'value': 'REIMS'},
        {'name': 'NEUILLY SUR SEINE', 'value': 'NEUILLY SUR SEINE'},
        {'name': 'MONTREUIL', 'value': 'MONTREUIL'},
        {'name': 'CLERMONT FERRAND', 'value': 'CLERMONT FERRAND'},
        {'name': 'LYON 2EME', 'value': 'LYON 2EME'},
        {'name': 'LYON 3EME', 'value': 'LYON 3EME'},
        {'name': 'LYON 6EME', 'value': 'LYON 6EME'},
        {'name': 'LYON 7EME', 'value': 'LYON 7EME'},
        {'name': 'ROUEN', 'value': 'ROUEN'},
        {'name': 'VILLEURBANNE', 'value': 'VILLEURBANNE'},
        {'name': 'ANTIBES', 'value': 'ANTIBES'},
        {'name': 'TOURS', 'value': 'TOURS'},
        {'name': 'AVIGNON', 'value': 'AVIGNON'},
        {'name': 'ANGERS', 'value': 'ANGERS'},
        {'name': 'MARSEILLE 1', 'value': 'MARSEILLE 1'},
        {'name': 'MARSEILLE 6', 'value': 'MARSEILLE 6'},
        {'name': 'MARSEILLE 8', 'value': 'MARSEILLE 8'},
        {'name': 'METZ', 'value': 'METZ'},
        {'name': 'NANCY', 'value': 'NANCY'},
        {'name': 'LE MANS', 'value': 'LE MANS'},
        {'name': 'CAEN', 'value': 'CAEN'},
        {'name': 'BESANCON', 'value': 'BESANCON'},
        {'name': 'LIMOGES', 'value': 'LIMOGES'},
        {'name': 'SAINT PAUL', 'value': 'SAINT PAUL'},
        {'name': 'AMIENS', 'value': 'AMIENS'},
        {'name': 'BREST', 'value': 'BREST'},
        {'name': 'VERSAILLES', 'value': 'VERSAILLES'},
        {'name': 'LE HAVRE', 'value': 'LE HAVRE'},
        {'name': 'COURBEVOIE', 'value': 'COURBEVOIE'},
        {'name': 'ORLEANS', 'value': 'ORLEANS'},
        {'name': 'LA ROCHELLE', 'value': 'LA ROCHELLE'},
        {'name': 'MULHOUSE', 'value': 'MULHOUSE'},
        {'name': 'LEVALLOIS PERRET', 'value': 'LEVALLOIS PERRET'},
        {'name': 'BEZIERS', 'value': 'BEZIERS'},
        {'name': 'SAINT MAUR DES FOSSES', 'value': 'SAINT MAUR DES FOSSES'},
        {'name': 'SAINT PIERRE', 'value': 'SAINT PIERRE'},
        {'name': 'PAU', 'value': 'PAU'},
        {'name': 'ASNIERES SUR SEINE', 'value': 'ASNIERES SUR SEINE'},
        {'name': 'BAIE MAHAULT', 'value': 'BAIE MAHAULT'},
        {'name': 'AUBERVILLIERS', 'value': 'AUBERVILLIERS'},
        {'name': 'VALENCE', 'value': 'VALENCE'},
        {'name': 'ROUBAIX', 'value': 'ROUBAIX'},
        {'name': 'AJACCIO', 'value': 'AJACCIO'},
        {'name': 'ARGENTEUIL', 'value': 'ARGENTEUIL'},
        {'name': 'NANTERRE', 'value': 'NANTERRE'},
        {'name': 'POITIERS', 'value': 'POITIERS'},
        {'name': 'RUEIL MALMAISON', 'value': 'RUEIL MALMAISON'},
        {'name': 'MERIGNAC', 'value': 'MERIGNAC'},
        {'name': 'HYERES', 'value': 'HYERES'},
        {'name': 'SAINT MARTIN', 'value': 'SAINT MARTIN'},
        {'name': 'LE LAMENTIN', 'value': 'LE LAMENTIN'},
        {'name': 'CAYENNE', 'value': 'CAYENNE'},
        {'name': 'NARBONNE', 'value': 'NARBONNE'},
        {'name': 'PANTIN', 'value': 'PANTIN'},
        {'name': 'ISSY LES MOULINEAUX', 'value': 'ISSY LES MOULINEAUX'},
        {'name': 'QUIMPER', 'value': 'QUIMPER'},
        {'name': 'FREJUS', 'value': 'FREJUS'},
        {'name': 'SAINT OUEN', 'value': 'SAINT OUEN'},
        {'name': 'COLMAR', 'value': 'COLMAR'},
        {'name': 'CAGNES SUR MER', 'value': 'CAGNES SUR MER'},
    ];
}
